# -*- coding: utf-8 -*-
'''"""Admission.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hJW5iDLxEXxwRvWJKQd6kWugJcJmawqm
"""'''

import pandas as pd

admission=pd.read_csv("https://github.com/YBI-Foundation/Dataset/raw/main/Admission%20Chance.csv")

admission.info

admission.head

admission.describe

admission.columns

y=admission['Chance of Admit ']
x=admission.drop(['Chance of Admit ','Serial No'],axis=1)

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.7,random_state=2528)

from sklearn.linear_model import LinearRegression

model=LinearRegression()

model.fit(x_train,y_train)

model.coef_

model.intercept_

y_pred=model.predict(x_test)

y_pred

from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error, mean_squared_error

mean_absolute_error(y_test,y_pred)

mean_absolute_percentage_error(y_test,y_pred)

mean_squared_error(y_test,y_pred)

