# -*- coding: utf-8 -*-
"""SalaryPred.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uzvyFfUJCyWKzDxbS-LbVSslCroEE918
"""

#step1:import library
import pandas as pd

#step 2: import data
salary = pd.read_csv('https://github.com/YBI-Foundation/Dataset/raw/main/Salary%20Data.csv')

salary.head()

salary.info()

salary.describe()

salary.columns

salary.shape

#step3: define target (y) and features(x)
y = salary['Salary']
x = salary[['Experience Years']]

x.shape

y.shape

#step 4:train test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,random_state=2529)

x_train.shape,x_test.shape,y_train.shape,y_test.shape
x_train



#step 5:select model
from sklearn.linear_model import LinearRegression
model=LinearRegression()

model.fit(x_train,y_train)

model.intercept_

model.coef_

y_pred=model.predict(x_test)

y_pred

from sklearn.metrics import mean_absolute_percentage_error

acc=mean_absolute_percentage_error(y_test,y_pred)

print("accuracy=",100-100*acc)

